### ISSUE TITLE
Question about logo

### ISSUE THREAD

**Issue by hubertlepicki** [amberframework/amberframework.org#10]
Hey there Amber framework team from AmberBit company from Poland.

It was pointed out to me recently that our logo looks awful like your logo. I checked this repo and also our history of correspondence with a designer who we asked to design a new logo for us in 2018, and indeed, the "gem" of the amber is almost identical in structure although different in colors on both logos.

This is your logo:
![logo](https://user-images.githubusercontent.com/33274/158808399-c6a32048-0550-4f01-9918-458792a0c845.png)

This is our logo:
![krysztal_rgb](https://user-images.githubusercontent.com/33274/158808333-6deccbda-c5cd-4760-b483-595232343e97.png)

If you look at the gem structure on both it's close to identical, with our maybe slightly changed.

I checked the correspondence with the designer, and we got her initial work delivered for us on Apr 5, 2018. I don't know when you started using the logo, the repository says Jun 18, 2018, but the commit says "Initial commit (repo cleanup)]" so it very well may have been there before.

https://github.com/amberframework/amberframework.org/blob/master/public/assets/img/amber.png

I would like to do something to reconcile the situation so that only either us or you end up using logo, and figured it'd be fair to the side that got their logo done later to alter it.

I don't suspect either your or our designer "stole" the logo from each other, I think they both may be using the same underlying vector graphics of possibly public domain nature (?) I don't know.

But anyway, from the point of view of corporate branding and just to avoid confusing AmberBit with Amber project I would like to make a change on either side.

Could you let me know when, and possibly how, you had your logo designed? Again, that's related to my proposal to whoever got it done first to keep it, but I am open to other suggestions on how we can resolve the issue.

**Comment by crimson-knight** [comment]
hi @hubertlepicki 

The Amber brand details can be found here: https://github.com/amberframework/amber-brand

The original date for the files being pushed into the repo looks to be late 2017, so I'm going to take a guess that the Amber logo was first.

I'm open to changing the Amber Framework branding, I'm a new contributor/maintainer trying to do more for the project and one of those things is modernizing the branding a bit.
