### ISSUE TITLE
Refactor current guide Implementation

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amberframework.org#42]
I think the current guide is awesome but, current implementation is loading documentation using ajax.

The XHR request has a problem, we can't use proper permalinks to documentation. By example, on introduction page we have a link to https://amberframework.org/getting-started/README.md and the response is 404.

My idea is to add `/:path` route, using an administration resource to manage route/source associations.

![screenshot_20171014_011738](https://user-images.githubusercontent.com/3067335/31573245-795c9258-b07d-11e7-9819-ebcaf8291173.png)

On `config/routes.cr`:

```crystal
routes :web do
  get "/:path", HomeController, :guides_path
  resources "/admin-guide", AdminGuidesController
end
```

On `src/controllers/home_controller.cr`

```crystal
class HomeController < ApplicationController
  def guides_path
    if source = AdminGuidesPath.find params["path"]
      render("guides_path.slang")
    else
      raise Amber::Exceptions::RouteNotFound.new(context.request)
    end
  end
end
```

### Advantages:

- Use paths instead of ids
- Allow to implement headers permalink
- Avoid wrong anchor links
- Improves history navigation (currently broken)
- Improves accessibility
- Allow to modify title using backend
- Keep using latest original source
- Don't storage documentation data, only path/source associations 

### Disadvantages: 

- Needs a database
- Needs an authentication handler

## Alternatives designs:

Also we can use a hash structure to storage relations embed on source code, but I don't know if would be a good practice

```crystal
  HASH_WITH_PATH_SOURCE_ASOCIATIONS = {
    "/getting-started/Installation/create-new-app" => "https://raw.../Installation/create-new-app.md"
  }
  def guides_path
    if source = HASH_WITH_PATH_SOURCE_ASOCIATIONS[params["path"]]
      render("guides_path.slang")
    else
      raise Amber::Exceptions::RouteNotFound.new(context.request)
    end
  end
```

@eliasjpr @fridgerator @drujensen @elorest WDYT ?

**Comment by faustinoaq** [comment]
Also it would fix #40

**Comment by faustinoaq** [comment]
Also I think this will allow us to implement a search box easier.

**Comment by elorest** [comment]
Why not just render the markdown files ourself within the page? If crystal
markdown has limitations we could fix or work around them?

**Comment by faustinoaq** [comment]
Yeah My thoughts is current Crystal markdown in std has some limitations, I wanted to use markd but it doesn't support tables yet. Maybe we can try using remarkdown https://github.com/veelenga/awesome-crystal/blob/master/README.md#markdowntext-processors

**Comment by elorest** [comment]
That could be a good idea. Potentially we could even use a Javascript
markdown Library.

**Comment by eliasjpr** [comment]
Crystal markdown has other limitations other than tables, for example, the code tag does not render the language in some if not all cases.

I would vote up for cleaning things up and having the markdown file :markdown_path as per of the URI.

Great suggestion @faustinoaq

**Comment by elorest** [comment]
Won't this solution require us to duplicate links that are already contained within the markdown? Would this fix issue where images within the markdown aren't loading?

@eliasjpr I currently use STD Markdown on a code blog and have had no issue with code rendering perfectly.

**Comment by eliasjpr** [comment]
Give it a shot with Crystal markdown. I know that some files were not rendering. Also the js rendering seems to be rendering faster, this could just be a visual effect

**Comment by elorest** [comment]
https://github.com/showdownjs/showdown could also be a good option.

**Comment by eliasjpr** [comment]
The original JS markdown lib that it was using is one of the most widely accepted MD. What ever get this working correctly I on board.
