### ISSUE TITLE
Question: Why duplicate https://docs.amberframework.org at https://amberframework.org/guides

### ISSUE THREAD

**Issue by marksiemers** [amberframework/amberframework.org#53]
Is this for branding? It seems like a lot of work to update and maintain the `/guides` part of the site when AFAIK it is a branded and styled version of the GitBook publication.

**Comment by faustinoaq** [comment]
https://docs.amberframework.org  was first, we used Gitbook to write the guides even before this repo exist. Our styled guide implementation on new site is still work in progress, so we provide gitbook option if someone feels better reading and using gitbook features like searching, change font size and night mode.

**Comment by marksiemers** [comment]
That all makes sense, why not use ONLY the Gitbook version. Are there advantages to the guides version? Will they diverge at some point?

**Comment by elorest** [comment]
I believe that there actually the same. It's better for seo to have it on
the same subdomain though.

**Comment by faustinoaq** [comment]
We are using redirection now, Fixed!!!

(although we still keep gitbook under the hood)
