### ISSUE TITLE
amberframework.org has expired

### ISSUE THREAD

**Issue by zach** [amberframework/amberframework.org#9]
I noticed that the domain name amberframework.org has expired at 16:13:26 UTC today.

NB: I have made a $20 Liberapay payment to help defray costs.

**Comment by drujensen** [comment]
Thanks @zach! @eliasjpr I think you purchased the original one, right? `whois` has your name listed. @robacarp let's see if we can use this payment to help purchase the domain again.

**Comment by robacarp** [comment]
@zach thanks for letting us know!

**Comment by elorest** [comment]
Any word on this. I'm willing to just buy it right now if that would help. Hover.com shows it's unavailable though.

**Comment by robacarp** [comment]
Unfortunately the redemption process is extensive, and the domain won't be available on the public market for some time -- it may get snatched up by a domain squatter as well.

> When a domain expires, your website and mail service will stop functioning, and no changes can be made to the domain.
>
> However, for generic TLDs (.com, .net, .org, .biz, .info, etc.), you have a period of about 30 days at Namecheap after the actual expiration date during which you can still renew the domain at the regular rate. A full list of generic TLDs can be found on the Domain Name Search page.
>
> If you do not renew the domain within this grace period, it enters a redemption stage for 30 days (sometimes more) at the Registry. At this stage, the domain may be auctioned off by the upstream vendors.
>
> As an owner, you still have an option to return the domain at this stage (if it's not auctioned off) at a redemption fee (you can contact our Support team to check what would be the exact fee for your domain) plus its regular renewal cost. If the domain is not recovered from redemption, it enters a PendingDelete stage at the Registry for 5 days. On the 6th day, the domain should be released to the public for re-registration.
>
> Normally, generic TLDs get released approximately in 70-80 days (in rare cases, up to 120 days) after the expiration date if not returned from redemption and if not auctioned off.

[source](https://www.namecheap.com/support/knowledgebase/article.aspx/9916/2207/tlds-grace-periods)

**Comment by drujensen** [comment]
@eliasjpr Is listed as the owner.  Let me send an email and see if we can get him to repurchase it.  [edit]Interesting, now it's guarded.  I should have taken a screenshot.

**Comment by drujensen** [comment]
and now its back up.  Looks like @eliasjpr took care of it.

**Comment by elorest** [comment]
Nice. Thanks @eliasjpr :)
