### ISSUE TITLE
Create a pre-rendered solution for amber guides

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amberframework.org#98]
Ref: https://github.com/amberframework/online-docs/pull/74#discussion_r179912341

The idea is to replace the url fetching we have by a small database to allow us requesting a nice url with anchor feature and maybe integrated search :wink: .

**Comment by damianham** [comment]
Github has a markdown API to convert markdown to html so that may be the quick and easy way to do this.  Although there might then be issues with rate limits once amber becomes the most popular web framework ever!  :smile: 
Here is example usage https://gist.github.com/ttscoff/3732963

**Comment by eliasjpr** [comment]
We can can render the markdown and serve the static version instead, there is no need to every time render the markdown.

**Comment by faustinoaq** [comment]
@eliasjpr Yeah, just like `crystal docs` does :+1:

**Comment by faustinoaq** [comment]
@sdiq shared this on [gitter](https://gitter.im/amberframework/amber?at=5aef2da300dc4888049c5ba8)

> I see something breaks when right clicking on the guides. The 'guides' part is missing in the right clicked url.

![image](https://user-images.githubusercontent.com/3067335/39733684-7d6a499a-5239-11e8-8a90-3c88af24be6c.png)

I guess we can use gitbook as workaround. Sany other tools, frameworks and languages use it, 

We can cleanup and update our current [amber gitbook](https://legacy.gitbook.com/book/amberframework/amberframework/details)

I think a gitbook is easier to maintain for now

Maybe we can use the new nice gitbook, WDYT?

![screenshot_20180507_210750](https://user-images.githubusercontent.com/3067335/39733952-b4cc300a-523a-11e8-9ac8-7df16198c57c.png)

Ref: https://www.gitbook.com/

WDYT?

**Comment by faustinoaq** [comment]
Just look at https://redux.js.org/introduction :sparkles:

**Comment by faustinoaq** [comment]
We are using https://amberframework.gitbook.io/amber/getting-started now :tada:
